const data = {
  products: [
    {
      name: "Kennel Winter Warm House",
      slug: "Kennel Winter Warm House",
      category: "beds",
      image: "./images/bed1.png",
      price: "$15.99",
      stock: "11",
      brand: "pet kennel",
      rating: 4.5,
      numReviews: 8,
      description: "high quality bed",
    },
    {
      name: "Soft Pet Nest Kennel",
      slug: "Soft Pet Nest Kennel",
      category: "beds",
      image: "./images/bed2.png",
      price: "$31.99",
      stock: "15",
      brand: "pet kennel",
      rating: 4.5,
      numReviews: 8,
      description: "high quality bed",
    },
    {
      name: "Pet Kennel Mattress",
      slug: "Pet Kennel Mattress",
      category: "beds",
      image: "./images/bed3.png",
      price: "$20",
      stock: "5",
      brand: "pet kennel",
      rating: 4.5,
      numReviews: 13,
      description: "high quality bed",
    },
    {
      name: "Winter Puppy Kennel",
      slug: "Winter Puppy Kennel",
      category: "beds",
      image: "./images/bed4.png",
      price: "$20",
      stock: "6",
      brand: "pet kennel",
      rating: 4.5,
      numReviews: 2,
      description: "high quality bed",
    },
  ],
};

export default data;
